### PR TITLE
Created Aastha.md for HactoberFest 2020

### PR DESCRIPTION
**Pull request by Aastha3348**
Here is my Pull Request for HactoberFest. Merge the pull request

### CODE REVIEW

**Comment by arpancodes** [comment]
Hey please add courses! not a search results page for a topic. Please read README again

**Comment by Aastha3348** [comment]
Okay I will. Thankyou .

**Comment by Aastha3348** [comment]
Hey!! I've updated my readme. Kindly check if its up to the mark  for HacktoberFest PR

**Comment by arpancodes** [comment]
thanks!

**Pull request merged**
